CREATE DATABASE IF NOT EXISTS blog_pupo
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE blog_pupo;

CREATE TABLE IF NOT EXISTS users (
    idUser INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    user VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    picture VARCHAR(100) NOT NULL DEFAULT 'placeholder.svg',
    registrationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    INDEX idx_users_ativo (ativo)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS posts (
    idPost INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    datePost TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idUser INT UNSIGNED NOT NULL,
    CONSTRAINT fk_posts_users
      FOREIGN KEY (idUser) REFERENCES users(idUser) ON DELETE CASCADE,
    INDEX idx_posts_date (datePost),
    INDEX idx_posts_user (idUser)
) ENGINE=InnoDB;
